[package]
name = "snapshotify"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
compose-rs = "0.0.3"
google-cloud-storage = "0.22.1"
lz4 = "1.27.0"
structopt = "0.3.26"
tar = "0.4.42"
tokio = { version = "1.40.0", features = ["full"] }
tokio-cron-scheduler = { version = "0.13.0", features = ["signal"] }
tokio-util = { version = "0.7", features = ["codec"] }
walkdir = "2.5.0"
